name: Build and upload release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        shell: cmd
        run: build.bat

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/studio-brightness.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
